import { getDashboardData } from "@/services/dashboard";
import { redirect } from "next/navigation";
import { requireSession, roleLabel } from "@/lib/auth-guard";
import { logout } from "@/app/login/actions";
import { BankDistributionChart, CashFlowChart } from "@/components/dashboard-charts";

const money = (amount: number) => new Intl.NumberFormat("tr-TR", { style: "currency", currency: "TRY" }).format(amount);

export default async function Home() {
  const session = await requireSession();
  if (session.role === "VIEWER") redirect("/reports");
  const data = await getDashboardData();
  const initials = session.name.split(/\s+/).map((part) => part[0]).slice(0, 2).join("").toUpperCase();
  const metrics = [["Bugünkü toplam giriş", money(data.todayIncome), "Bugünün onaylanmış hareketleri", "#14835d"], ["Bugünkü toplam çıkış", money(data.todayExpense), "Bugünün onaylanmış hareketleri", "#c75151"], ["Bugünkü net nakit akışı", money(data.todayIncome - data.todayExpense), "Girişler eksi çıkışlar", "#14835d"], ["Bu ay net", money(data.monthIncome - data.monthExpense), "Bu ayın onaylanmış hareketleri", "#14835d"]];
  return <main className="min-h-screen bg-[#f6f7f8] text-[#263441]">
    <header className="border-b border-[#e5e9ee] bg-white px-6 py-4 lg:px-10"><div className="mx-auto flex max-w-[1500px] items-center justify-between"><div><p className="text-[10px] font-bold tracking-[.8px] text-[#8993a0]">CANLI VERİ AKIŞI</p><h1 className="mt-1 text-xl font-semibold">Finans özeti</h1></div><div className="flex items-center gap-4 text-xs text-[#697787]"><span className="hidden md:block"><i className={`mr-2 inline-block h-2 w-2 rounded-full ${data.connected ? "bg-[#19a878]" : "bg-[#d39b37]"}`} />{data.lastCheckedAt ? `Son kontrol: ${data.lastCheckedAt.toLocaleString("tr-TR")}` : data.connected ? "Henüz mail işlenmedi" : "Veritabanı bağlı değil"}</span><span className="grid h-8 w-8 place-items-center rounded-full bg-[#e6a072] text-[10px] font-bold text-white">{initials}</span><span className="hidden sm:block"><b className="text-[#2c3945]">{session.name}</b><small className="block">{roleLabel[session.role]}</small></span><form action={logout}><button className="rounded border border-[#dce2e8] px-2 py-1 text-[10px] text-[#5f6d7c]" type="submit">Çıkış</button></form></div></div></header>
    <div className="mx-auto max-w-[1500px] p-5 lg:p-8"><nav className="mb-7 flex gap-2 overflow-auto text-xs font-medium"><a className="rounded bg-[#263746] px-4 py-2 text-white" href="/">Dashboard</a><a className="px-4 py-2 text-[#617080]" href="#transactions">İşlemler</a><a className="px-4 py-2 text-[#617080]" href="/review">İnceleme Bekleyenler{data.reviewCount > 0 ? <b className="rounded-full bg-[#d4653c] px-1.5 py-0.5 text-[10px] text-white">{data.reviewCount}</b> : null}</a><a className="px-4 py-2 text-[#617080]" href="/admin/bank-accounts">Banka Hesapları</a><a className="px-4 py-2 text-[#617080]" href="/reports">Raporlar</a><a className="px-4 py-2 text-[#617080]" href="/tours">Turlar</a><a className="px-4 py-2 text-[#617080]" href="/admin/email-rules">Mail Kuralları</a><a className="px-4 py-2 text-[#617080]" href="/logs">Loglar</a></nav>
      <section id="dashboard" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([title, amount, detail, color]) => <article className="rounded-md border border-[#e5e9ee] bg-white p-5" key={title}><p className="text-xs text-[#6f7c8b]">{title}</p><strong className="my-3 block text-2xl tracking-normal">{amount}</strong><small style={{ color }} className="text-[11px]">{detail}</small></article>)}</section>
      <section className="mt-5 grid gap-4 lg:grid-cols-[1.6fr_1fr]"><article className="rounded-md border border-[#e5e9ee] bg-white p-5"><div className="flex justify-between"><div><h2 className="font-semibold">Nakit akışı</h2><p className="mt-1 text-[11px] text-[#84909d]">Son 7 gün, onaylanmış hareketler</p></div></div><div className="mt-6"><CashFlowChart data={data.dailyFlow} /></div><p className="mt-3 text-[11px] text-[#758190]"><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#208d69]" />Para girişi <i className="ml-5 mr-1 inline-block h-2 w-2 rounded-full bg-[#d4695b]" />Para çıkışı</p></article><article className="rounded-md border border-[#e5e9ee] bg-white p-5"><h2 className="font-semibold">Banka dağılımı</h2><p className="mt-1 text-[11px] text-[#84909d]">Bu ay hesap hareketleri</p><div className="mt-5"><BankDistributionChart data={data.bankDistribution} /></div></article></section>
      <section id="accounts" className="mt-7"><div className="flex items-end justify-between"><div><h2 className="font-semibold">Banka hesapları</h2><p className="mt-1 text-[11px] text-[#84909d]">Bu ayın onaylanmış hareket özeti</p></div><a className="text-xs font-semibold text-[#168360]" href="/admin/bank-accounts">Tüm hesapları görüntüle →</a></div><div className="mt-4 grid gap-4 md:grid-cols-3">{data.bankSummaries.length ? data.bankSummaries.map((bank) => <article className="rounded-md border border-[#e5e9ee] bg-white p-5" key={bank.bank}><strong>{bank.bank}</strong><dl className="mt-5 grid grid-cols-3 text-xs"><div><dt className="text-[#8b96a2]">Giriş</dt><dd className="mt-1 font-bold text-[#14835d]">{money(bank.income)}</dd></div><div><dt className="text-[#8b96a2]">Çıkış</dt><dd className="mt-1 font-bold text-[#c75151]">{money(bank.expense)}</dd></div><div><dt className="text-[#8b96a2]">Net</dt><dd className={`mt-1 font-bold ${bank.net >= 0 ? "text-[#14835d]" : "text-[#c75151]"}`}>{money(bank.net)}</dd></div></dl></article>) : <div className="col-span-full rounded-md border border-dashed border-[#cfd7dd] bg-white px-5 py-10 text-center text-sm text-[#718091]">Bu ay için banka hareketi bulunamadı.</div>}</div></section>
      <section id="transactions" className="mt-7 overflow-hidden rounded-md border border-[#e5e9ee] bg-white"><div className="flex items-center justify-between p-5"><div><h2 className="font-semibold">Son işlemler</h2><p className="mt-1 text-[11px] text-[#84909d]">E-posta işleme akışından gelen hareketler</p></div><div className="flex gap-2"><button className="rounded border border-[#dce2e8] px-3 py-2 text-[11px] text-[#5f6d7c]">Filtrele</button><button className="rounded bg-[#24795f] px-3 py-2 text-[11px] text-white">Dışa aktar</button></div></div><div className="overflow-auto"><table className="w-full min-w-[1100px] border-t border-[#e5e9ee] text-left text-[11px]"><thead className="bg-[#fbfcfc] text-[10px] text-[#8994a0]"><tr>{["Tarih / Saat", "Banka", "İşlem", "Giriş / Çıkış", "Tutar", "Gönderen / Alıcı", "Açıklama", "Kategori", "Durum"].map(x => <th className="whitespace-nowrap p-3 font-semibold" key={x}>{x}</th>)}</tr></thead><tbody>{data.transactions.length ? data.transactions.map(row => <tr className="border-t border-[#eef0f2]" key={row.id}><td className="whitespace-nowrap p-3">{row.date}<small className="ml-2 text-[#8994a0]">{row.time}</small></td><td className="whitespace-nowrap p-3 font-bold">{row.bank}</td><td className="whitespace-nowrap p-3">{row.type}</td><td className="whitespace-nowrap p-3">{row.direction === "IN" ? "Giriş" : "Çıkış"}</td><td className={`whitespace-nowrap p-3 font-bold ${row.direction === "IN" ? "text-[#14835d]" : "text-[#c75151]"}`}>{row.direction === "IN" ? "+" : "−"}{money(row.amount)}</td><td className="whitespace-nowrap p-3 font-bold">{row.counterparty}</td><td className="whitespace-nowrap p-3">{row.description}</td><td className="whitespace-nowrap p-3">{row.category}</td><td className="whitespace-nowrap p-3">{row.status}</td></tr>) : <tr><td className="p-8 text-center text-[#84909d]" colSpan={9}>{data.connected ? "Gösterilecek işlem bulunamadı." : "Neon DATABASE_URL tanımlandığında hareketler burada canlı olarak görüntülenecek."}</td></tr>}</tbody></table></div></section>
    </div>
  </main>;
}
