import Link from "next/link";
import {
  ArrowDownRight, ArrowUpRight, Bell, Building2, ChevronRight, CircleDollarSign,
  FileBarChart, Landmark, ListFilter, LogOut, MailCheck, PieChart, ScrollText,
  Settings2, ShieldCheck, Tags, Ticket, WalletCards,
} from "lucide-react";
import type { DashboardData } from "@/services/dashboard";
import type { Role } from "@/lib/session-token";
import { normalizeCurrency } from "@/lib/currency";
import { BankDistributionChart, CashFlowChart } from "./dashboard-charts";

const roleLabel: Record<Role, string> = { ADMIN: "Yönetici", FINANCE: "Finans", VIEWER: "Görüntüleyici" };

function formatMoney(amount: number, currency = "TRY", compact = false) {
  return new Intl.NumberFormat("tr-TR", {
    style: "currency", currency: normalizeCurrency(currency),
    notation: compact ? "compact" : "standard", maximumFractionDigits: compact ? 1 : 2,
  }).format(amount);
}

function MetricCard({ label, amount, caption, direction }: { label: string; amount: number; caption: string; direction: "in" | "out" | "net" }) {
  const isIn = direction !== "out";
  const tone = isIn ? "text-[#167b5d]" : "text-[#c15a56]";
  const Icon = direction === "net" ? WalletCards : isIn ? ArrowDownRight : ArrowUpRight;
  return <article className="border-l border-t border-[#e6e8eb] bg-white p-5 first:rounded-tl-lg last:rounded-tr-lg sm:border-l-0 sm:border-r sm:first:rounded-none sm:last:rounded-none xl:first:rounded-tl-lg xl:last:rounded-tr-lg"><div className="flex items-start justify-between"><p className="text-[11px] font-semibold uppercase tracking-[.08em] text-[#7d8995]">{label}</p><span className={`grid h-8 w-8 place-items-center rounded-full ${isIn ? "bg-[#e8f4ef]" : "bg-[#f9eceb]"} ${tone}`}><Icon size={15} /></span></div><strong className="mt-5 block text-[22px] font-semibold tracking-normal text-[#243241]">{formatMoney(amount)}</strong><p className={`mt-2 text-[11px] ${tone}`}>{caption}</p></article>;
}

export function FinanceDashboard({ data, name, role, onLogout }: { data: DashboardData; name: string; role: Role; onLogout: () => Promise<void> }) {
  const initials = name.split(/\s+/).map((part) => part[0]).slice(0, 2).join("").toUpperCase();
  const foreign = data.currencySummaries.filter((item) => item.currency !== "TRY");
  const navigation = [
    ["Dashboard", "/", PieChart], ["İşlemler", "#transactions", ScrollText], ["İnceleme", "/review", ShieldCheck],
    ["Banka Hesapları", "/admin/bank-accounts", Landmark], ["Raporlar", "/reports", FileBarChart],
    ["Turlar", "/tours", Ticket], ["Mail Kuralları", "/admin/email-rules", Tags], ["Loglar", "/logs", MailCheck],
  ] as const;

  return <div className="min-h-screen bg-[#f4f6f7] text-[#273544]">
    <aside className="fixed inset-y-0 hidden w-[236px] flex-col border-r border-[#263748] bg-[#1d2b39] px-4 py-6 lg:flex">
      <Link className="flex items-center gap-2 px-2 text-lg font-semibold text-white" href="/"><span className="grid h-7 w-7 place-items-center rounded-md bg-[#de7441] text-sm">e</span>ejder<span className="font-normal text-[#93a2ae]">finans</span></Link>
      <p className="mt-12 px-2 text-[10px] font-bold tracking-[.16em] text-[#78909f]">OPERASYON</p>
      <nav className="mt-3 space-y-1">{navigation.map(([label, href, Icon], index) => <Link className={`flex h-10 items-center gap-3 rounded-md px-3 text-xs font-medium ${index === 0 ? "bg-[#314658] text-white" : "text-[#b5c1cb] hover:bg-[#273a4b] hover:text-white"}`} href={href} key={label}><Icon size={16} className={index === 0 ? "text-[#ed8a51]" : "text-[#a1b1bd]"} />{label}{label === "İnceleme" && data.reviewCount > 0 ? <span className="ml-auto rounded-full bg-[#d76b42] px-1.5 py-0.5 text-[10px] text-white">{data.reviewCount}</span> : null}</Link>)}</nav>
      <div className="mt-auto rounded-md border border-[#3b4e5e] p-3 text-[#b9c6d0]"><div className="flex items-center gap-2"><Settings2 size={15} /><span className="text-xs font-semibold">Sistem durumu</span></div><p className="mt-2 text-[11px] text-[#91a2af]">IMAP akışı aktif</p><span className={`mt-2 inline-flex items-center gap-1 text-[10px] ${data.connected ? "text-[#65c79d]" : "text-[#e9ad5f]"}`}><i className="h-1.5 w-1.5 rounded-full bg-current" />{data.connected ? "Veritabanı bağlı" : "Bağlantı bekleniyor"}</span></div>
    </aside>

    <main className="lg:ml-[236px]">
      <header className="sticky top-0 z-10 border-b border-[#e2e7ea] bg-white/95 px-5 py-4 backdrop-blur lg:px-9"><div className="mx-auto flex max-w-[1540px] items-center justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[.13em] text-[#7d8995]">NAKİT YÖNETİMİ</p><h1 className="mt-1 text-xl font-semibold">Finans kontrol merkezi</h1></div><div className="flex items-center gap-3"><div className="hidden text-right md:block"><p className="text-[11px] text-[#738190]">{data.lastCheckedAt ? `Son posta taraması: ${data.lastCheckedAt.toLocaleString("tr-TR")}` : "Henüz posta taraması yok"}</p><p className="mt-0.5 text-[10px] font-medium text-[#238060]">Canlı veri akışı</p></div><button aria-label="Bildirimler" className="grid h-9 w-9 place-items-center rounded-md border border-[#dce3e7] text-[#637281]"><Bell size={16} /></button><div className="flex items-center gap-2 border-l border-[#e5e9ec] pl-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#e9a677] text-[11px] font-bold text-white">{initials}</span><div className="hidden sm:block"><p className="text-xs font-semibold">{name}</p><p className="text-[10px] text-[#7c8995]">{roleLabel[role]}</p></div><form action={onLogout}><button aria-label="Çıkış yap" className="ml-1 text-[#7c8995] hover:text-[#c15a56]" title="Çıkış yap" type="submit"><LogOut size={16} /></button></form></div></div></div></header>

      <div className="mx-auto max-w-[1540px] p-5 lg:p-9">
        <section className="overflow-hidden rounded-lg border border-[#e1e6e9] bg-white shadow-[0_1px_2px_rgba(24,39,55,.03)]"><div className="flex flex-col gap-3 border-b border-[#e9edf0] px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold">TRY nakit pozisyonu</h2><p className="mt-1 text-[11px] text-[#7d8995]">Kur dönüşümü uygulanmadan, yalnızca Türk Lirası hareketleri</p></div><Link className="inline-flex items-center gap-1 text-xs font-semibold text-[#167b5d]" href="/reports">Detaylı rapor <ChevronRight size={14} /></Link></div><div className="grid sm:grid-cols-2 xl:grid-cols-4"><MetricCard amount={data.todayIncome} caption="Bugünün onaylanmış girişleri" direction="in" label="Bugün giriş" /><MetricCard amount={data.todayExpense} caption="Bugünün onaylanmış çıkışları" direction="out" label="Bugün çıkış" /><MetricCard amount={data.todayIncome - data.todayExpense} caption="Günlük net nakit akışı" direction="net" label="Bugün net" /><MetricCard amount={data.monthIncome - data.monthExpense} caption="Bu ayın net pozisyonu" direction="net" label="Bu ay net" /></div></section>

        {foreign.length ? <section className="mt-5 border-y border-[#dce4e8] bg-[#eaf0f2] py-4"><div className="flex items-center gap-2"><CircleDollarSign size={16} className="text-[#4d7899]" /><div><h2 className="text-sm font-semibold">Döviz portföyü</h2><p className="text-[11px] text-[#6f7f8b]">Bu ay, kur dönüşümü olmadan para birimi bazında</p></div></div><div className="mt-4 grid gap-px overflow-hidden rounded-md border border-[#dbe3e7] bg-[#dbe3e7] sm:grid-cols-2 xl:grid-cols-4">{foreign.map((summary) => <article className="bg-white p-4" key={summary.currency}><div className="flex items-center justify-between"><strong className="text-sm">{summary.currency}</strong><span className="rounded bg-[#edf2f5] px-2 py-1 text-[10px] font-semibold text-[#527087]">AYLIK</span></div><p className="mt-3 text-lg font-semibold">{formatMoney(summary.net, summary.currency)}</p><div className="mt-3 flex gap-4 text-[10px]"><span className="text-[#167b5d]">Giriş {formatMoney(summary.income, summary.currency, true)}</span><span className="text-[#c15a56]">Çıkış {formatMoney(summary.expense, summary.currency, true)}</span></div></article>)}</div></section> : null}

        <section className="mt-6 grid gap-5 xl:grid-cols-[1.7fr_1fr]"><article className="rounded-lg border border-[#e1e6e9] bg-white p-5"><div className="flex items-start justify-between"><div><h2 className="text-sm font-semibold">Haftalık nakit akışı</h2><p className="mt-1 text-[11px] text-[#7d8995]">TRY, son 7 gün</p></div><span className="rounded bg-[#eff5f2] px-2 py-1 text-[10px] font-semibold text-[#237b5d]">ONAYLANMIŞ</span></div><div className="mt-5"><CashFlowChart data={data.dailyFlow} /></div><div className="mt-1 flex gap-5 text-[10px] text-[#71808d]"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#208d69]" />Giriş</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#d4695b]" />Çıkış</span></div></article><article className="rounded-lg border border-[#e1e6e9] bg-white p-5"><div><h2 className="text-sm font-semibold">Banka payı</h2><p className="mt-1 text-[11px] text-[#7d8995]">TRY işlem hacmine göre</p></div><div className="mt-6"><BankDistributionChart data={data.bankDistribution} /></div></article></section>

        <section className="mt-7"><div className="flex items-end justify-between"><div><p className="text-[10px] font-bold tracking-[.13em] text-[#7d8995]">HESAPLAR</p><h2 className="mt-1 text-base font-semibold">Banka bazlı görünüm</h2></div><Link className="text-xs font-semibold text-[#167b5d]" href="/admin/bank-accounts">Hesapları yönet <ChevronRight className="inline" size={14} /></Link></div><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.bankSummaries.length ? data.bankSummaries.map((bank) => <article className="rounded-lg border border-[#e1e6e9] bg-white p-5" key={bank.bank}><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-md bg-[#ecf1f3] text-[#4d7899]"><Building2 size={15} /></span><strong className="text-sm">{bank.bank}</strong></div><span className="text-[10px] text-[#82909b]">TRY</span></div><dl className="mt-5 grid grid-cols-3 gap-2 text-xs"><div><dt className="text-[#8995a0]">Giriş</dt><dd className="mt-1 font-semibold text-[#167b5d]">{formatMoney(bank.income, "TRY", true)}</dd></div><div><dt className="text-[#8995a0]">Çıkış</dt><dd className="mt-1 font-semibold text-[#c15a56]">{formatMoney(bank.expense, "TRY", true)}</dd></div><div><dt className="text-[#8995a0]">Net</dt><dd className={`mt-1 font-semibold ${bank.net >= 0 ? "text-[#167b5d]" : "text-[#c15a56]"}`}>{formatMoney(bank.net, "TRY", true)}</dd></div></dl></article>) : <div className="col-span-full rounded-lg border border-dashed border-[#cbd5db] bg-white px-5 py-10 text-center text-sm text-[#778692]">Bu ay için TRY banka hareketi bulunamadı.</div>}</div></section>

        <section className="mt-7 overflow-hidden rounded-lg border border-[#e1e6e9] bg-white" id="transactions"><div className="flex flex-col gap-3 border-b border-[#e8ecef] p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-bold tracking-[.13em] text-[#7d8995]">HAREKETLER</p><h2 className="mt-1 text-base font-semibold">Son işlenen işlemler</h2></div><div className="flex gap-2"><Link className="inline-flex items-center gap-2 rounded-md border border-[#dbe2e6] px-3 py-2 text-xs font-semibold text-[#536473]" href="/reports"><ListFilter size={14} />Filtrele</Link><Link className="inline-flex items-center gap-2 rounded-md bg-[#1f765b] px-3 py-2 text-xs font-semibold text-white" href="/reports">Raporlara git <ChevronRight size={14} /></Link></div></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead className="bg-[#f9fafb]"><tr>{["Tarih", "Banka", "İşlem", "Yön", "Tutar", "Karşı taraf", "Açıklama", "Kategori"].map((label) => <th className="px-5 py-3 text-[10px] font-bold tracking-[.05em] text-[#87939e]" key={label}>{label}</th>)}</tr></thead><tbody>{data.transactions.length ? data.transactions.map((transaction) => <tr className="border-t border-[#edf0f2] text-xs" key={transaction.id}><td className="whitespace-nowrap px-5 py-4"><p className="font-medium">{transaction.date}</p><p className="mt-1 text-[10px] text-[#8e9aa4]">{transaction.time}</p></td><td className="whitespace-nowrap px-5 py-4 font-semibold">{transaction.bank}</td><td className="whitespace-nowrap px-5 py-4 text-[#5f6f7c]">{transaction.type}</td><td className="px-5 py-4"><span className={transaction.direction === "IN" ? "inline-flex items-center gap-1 rounded-full bg-[#e8f4ef] px-2 py-1 text-[10px] font-semibold text-[#167b5d]" : "inline-flex items-center gap-1 rounded-full bg-[#f9eceb] px-2 py-1 text-[10px] font-semibold text-[#c15a56]"}>{transaction.direction === "IN" ? <ArrowDownRight size={12} /> : <ArrowUpRight size={12} />}{transaction.direction === "IN" ? "Giriş" : "Çıkış"}</span></td><td className={transaction.direction === "IN" ? "whitespace-nowrap px-5 py-4 font-semibold text-[#167b5d]" : "whitespace-nowrap px-5 py-4 font-semibold text-[#c15a56]"}>{transaction.direction === "IN" ? "+" : "−"}{formatMoney(transaction.amount, transaction.currency)}</td><td className="max-w-48 truncate px-5 py-4 text-[#526372]">{transaction.counterparty}</td><td className="max-w-60 truncate px-5 py-4 text-[#526372]">{transaction.description}</td><td className="px-5 py-4"><span className="rounded bg-[#eef2f4] px-2 py-1 text-[10px] font-medium text-[#627482]">{transaction.category}</span></td></tr>) : <tr><td className="px-5 py-14 text-center text-sm text-[#7d8995]" colSpan={8}>Posta kutusundan işlenen hareketler burada görünür.</td></tr>}</tbody></table></div></section>
      </div>
    </main>
  </div>;
}
